/*
 * board.c
 *
 *  Created on: May 24, 2026
 *      Author: julius
 */

#include "stm32f411xe.h"
#include "utilities.h"

void init_board(void) {
    // Enable clock to GPIOA, GPIOB, and GPIOC
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

    // initialize pins for motor controllers
    MODIFY_FIELD(GPIOC->MODER, GPIO_MODER_MODER7, ESF_GPIO_MODER_OUTPUT);  // PC7  = STBY
    MODIFY_FIELD(GPIOA->MODER, GPIO_MODER_MODER9, ESF_GPIO_MODER_OUTPUT);  // PA9  = AIN1
    MODIFY_FIELD(GPIOA->MODER, GPIO_MODER_MODER8, ESF_GPIO_MODER_OUTPUT);  // PA8  = AIN2
    MODIFY_FIELD(GPIOB->MODER, GPIO_MODER_MODER6, ESF_GPIO_MODER_OUTPUT);  // PB6  = BIN1
    MODIFY_FIELD(GPIOA->MODER, GPIO_MODER_MODER7, ESF_GPIO_MODER_OUTPUT);  // PA7  = BIN2

    // `initialize pins for HC-SR04
    MODIFY_FIELD(GPIOB->MODER, GPIO_MODER_MODER9, ESF_GPIO_MODER_OUTPUT); // PB9 = TRIG
    MODIFY_FIELD(GPIOB->MODER, GPIO_MODER_MODER8, ESF_GPIO_MODER_INPUT); // PB8 = ECHO

    // reset all pins
    GPIOC->BSRR = GPIO_BSRR_BR_7;
    GPIOA->BSRR = GPIO_BSRR_BR_9;
    GPIOA->BSRR = GPIO_BSRR_BR_8;
    GPIOB->BSRR = GPIO_BSRR_BR_6;
    GPIOA->BSRR = GPIO_BSRR_BR_7;
    GPIOB->BSRR = GPIO_BSRR_BR_9;
}
