/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

#include "board.h"
#include "stm32f411xe.h"
#include "system_stm32f4xx.h"
#include "utilities.h"
#include "systick_timer.h"
#include "debug.h"


#define ULED_TIME_TICKS	20

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
//
//static void enable_fpu(void)
//{
//    /*
//     * Enable full access to CP10 and CP11.
//     * These are the Cortex-M4 floating-point coprocessors.
//     */
//    SCB->CPACR |= (3UL << 20) | (3UL << 22);
//
//    /*
//     * Ensure the change takes effect before executing
//     * any floating-point instructions.
//     */
//    __DSB();
//    __ISB();
//}


int main(void)
{

	init_board();
	MODIFY_FIELD(GPIOA->MODER, GPIO_MODER_MODER5, ESF_GPIO_MODER_OUTPUT);

	init_systick();
	init_usart2();


	DBG_PRINTF("Starting Program! \r\n");

//
//
//
//	ticktime_t last_uled_time = now();
//	bool uled_action = true;
//
//	while(1) {
//		if(time_reached(now(), last_uled_time + ULED_TIME_TICKS)) {
//			DBG_PRINTF("Time reached!\r\n");
//
//			// turn on board uled on and off
//			if(uled_action)
//				GPIOA->BSRR = GPIO_BSRR_BS_5;
//			else
//				GPIOA->BSRR = GPIO_BSRR_BR_5;
//
//			uled_action = !uled_action;
//			last_uled_time = now();
//
//		}
//	}

	while(1) { }

}
