/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <command_processor.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include "board.h"
#include "stm32f411xe.h"
#include "system_stm32f4xx.h"
#include "utilities.h"
#include "systick_timer.h"
#include "debug.h"
#include "usart.h"
#include "pwm.h"
#include "motor_control.h"
#include "cbfifo.h"
#include "command_processor.h"


//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
//
//static void enable_fpu(void)
//{
//    /*
//     * Enable full access to CP10 and CP11.
//     * These are the Cortex-M4 floating-point coprocessors.
//     */
//    SCB->CPACR |= (3UL << 20) | (3UL << 22);
//
//    /*
//     * Ensure the change takes effect before executing
//     * any floating-point instructions.
//     */
//    __DSB();
//    __ISB();
//}


//void print_clock_debug(void)
//{
//    uint32_t cfgr = RCC->CFGR;
//
//    uint32_t sws   = (cfgr >> 2)  & 0x3U;
//    uint32_t hpre  = (cfgr >> 4)  & 0xFU;
//    uint32_t ppre1 = (cfgr >> 10) & 0x7U;
//
//    DBG_PRINTF("RCC->CFGR = 0x%08lx\r\n", cfgr);
//    DBG_PRINTF("SWS   = %lu\r\n", sws);
//    DBG_PRINTF("HPRE  = %lu\r\n", hpre);
//    DBG_PRINTF("PPRE1 = %lu\r\n", ppre1);
//
//    if ((sws == 0U) && (hpre == 0U) && (ppre1 == 0U)) {
//        DBG_PRINTF("Clock looks like default HSI: SYSCLK=16MHz, HCLK=16MHz, PCLK1=16MHz\r\n");
//        DBG_PRINTF("TIM3 clock should be 16MHz\r\n");
//    } else {
//        DBG_PRINTF("Clock is not the simple default 16MHz setup. Need to decode more.\r\n");
//    }
//}

static cbfifo *bluetooth_cbfifo;
static cbfifo *debug_cbfifo;

int main(void)
{
	init_usart2(); // initialize usart for printing first
	init_board();
	init_systick();
	init_tim3_pwm();
	init_motor_controls();
	init_usart6();


	DBG_PRINTF("=============================== \r\n");
	DBG_PRINTF("Starting Program! \r\n");

//
//
//
//	// Set PWMB to speed 50
//	TIM3->CCR1 = 50;
//
//	// Set PWMA to speed 50
//	TIM2->CCR3 = 50;

	bluetooth_cbfifo = get_bluetooth_cbfifo();
	debug_cbfifo = get_debug_cbfifo();


	char command[QUEUE_SIZE];
	uint8_t command_index = 0;
	bool command_built = false;
	while(true) {
		command_built = build_command(command, &command_index, bluetooth_cbfifo);
		if(command_built) {
			// perform command
			run_command(command);
			memset(command, 0, QUEUE_SIZE);
			command_index = 0;
			command_built = false;
		}
	}

}
